[package]
name = "book_letter_counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
reqwest = "*"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "*"
